region         = "us-east-2"
project_name   = "getting-started"
frontend_image = "123456789012.dkr.ecr.us-east-2.amazonaws.com/frontend:staging"
backend_image  = "123456789012.dkr.ecr.us-east-2.amazonaws.com/backend:staging"
mysql_host     = "staging-db.xxxxxx.us-east-2.rds.amazonaws.com"
mysql_user     = "todos_user"
mysql_password = "supersecret"
mysql_db       = "todos_db"
