region         = "us-east-2"
project_name   = "getting-started"
frontend_image = "618889059366.dkr.ecr.us-east-2.amazonaws.com/frontend:latest"
backend_image  = "618889059366.dkr.ecr.us-east-2.amazonaws.com/backend:latest"
mysql_host     = "getting-started-db.xxxxxx.us-east-2.rds.amazonaws.com"
mysql_user     = "todos_user"
mysql_password = "supersecret"
mysql_db       = "todos_db"
